# -*- coding: utf-8 -*-
"""Ejemplo10_formatoEstandar.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Bvo38fW7fwkiMq54PVZW6S3VYdWhU2G0

# **Código para pasar a formato estándar:**
"""

import numpy as np

A = np.array([[-2, -1], [-2, -3]])
b = np.array([-12, -18])

m, n = A.shape
Aux = np.zeros([m, n+m])

# primeras n columnas
for j in range(0,n):
        Aux[:,j] = A[:,j]
# los unos

for i in range(0,m):
        Aux[i,n+i] = 1
        #si b[i] es negativo, entonces
        if b[i] < 0:
        # multiplicar por -1 las filas de Aux
          Aux[i,:] = -1.0*Aux[i,:]
        # multiplicar por -1 las filas de b
          b[i] = -b[i]

Aux, b